### ISSUE TITLE
`rebar3 ct` fails; `make ci_test` doesn't

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [g-andrade/locus#17] opened 2020-10-29 13:21 UTC
I'd expect `rebar3 ct` to not fail, but that's probably not your expectation. Will reply will clarify this 😄.

**Comment by g-andrade** [comment] 2020-10-29 14:35
The errors are caused by an unwarranted execution of the "remote HTTP tests"[*] group, which perform various checks of the ability to load databases directly from MaxMind. 

The execution of that particular test group is triggered depending on two conditions: 
1) the currently checked out commit is tagged (so that we won't run these network-expensive test cases during everyday development)
2) the license key is defined through an environment variable (`MAXMIND_LICENSE_KEY`)

Condition 2) is erroneously evaluating as true in your case; this is due to a [bad check](https://github.com/g-andrade/locus/blob/1.12.1/test/locus_SUITE.erl#L68-L70) of whether said environment variable is defined. This issue has likely been present since `1.9.0-beta` (when license key awareness was introduced.)

The fix is easy enough.

[*]: In addition to "local HTTP tests", in which a local web server serves the database files.

**Comment by g-andrade** [comment] 2020-10-29 14:36
As for the reason why `make ci_test` works: the "remote HTTP tests" group has been explicitly disabled for CI stuff for quite some time, as network access is not very reliable and the tests would often fail because of this.

**Comment by g-andrade** [comment] 2020-10-29 14:43
Fixed in 42cdbda and released under `1.2.2`.

**Closed as completed by g-andrade** 2020-10-29 14:43 UTC
Labels: bug
